# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install -g npm
  - init: npm init -y
  - init: npm install express nodemon dotenv mongoose crypto uuidv1 #runs during prebuild
    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
